spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 10000
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
        time-between-eviction-runs: 30000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  level:
    xyz:
      lizhaorong: trace
server:
  port: 7777